### ISSUE TITLE
NPE when adding hardware blocks on GHidra 9.0.4

### ISSUE THREAD

**Issue by brett-lempereur** [Gekkio/GhidraBoy#1]
When importing a ROM on GHidra 9.0.4, with add hardware blocks enabled, the following NPE occurs.  Disabling adding hardware blocks prior to importing allows it to succeed.

Traceback for `cgb_bios.bin`:
```
Error importing file: cgb_bios.bin
java.lang.NullPointerException
	at ghidra.app.util.MemoryBlockUtil.renameFragment(MemoryBlockUtil.java:613)
	at ghidra.app.util.MemoryBlockUtil.createUninitializedBlock(MemoryBlockUtil.java:149)
	at fi.gekkio.ghidraboy.Ghidra90Compat.createUninitializedBlock(Ghidra90Compat.java:33)
	at fi.gekkio.ghidraboy.GameBoyUtils.addHardwareBlocks(GameBoyUtils.java:38)
	at fi.gekkio.ghidraboy.GameBoyLoader.loadProgram(GameBoyLoader.java:133)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:114)
	at ghidra.plugin.importer.ImporterUtilities.doSingleImport(ImporterUtilities.java:360)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$6(ImporterDialog.java:363)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:93)
	at ghidra.util.task.Task.monitoredRun(Task.java:128)
	at ghidra.util.task.TaskLauncher.lambda$startBackgroundThread$2(TaskLauncher.java:315)
	at java.base/java.lang.Thread.run(Thread.java:835)

---------------------------------------------------
Build Date: 2019-May-16 1545 EDT
Ghidra Version: 9.0.4
Java Home: C:\Program Files\Java\jdk-12.0.1
JVM Version: Oracle Corporation 12.0.1
OS: Windows 10 10.0 amd64
Workstation: [omitted]
```

Traceback for `Gameboy Color Promotional Demo (J) [C].gbc`:
```
Error importing file: Gameboy Color Promotional Demo (J) [C].gbc
java.lang.NullPointerException
	at ghidra.app.util.MemoryBlockUtil.renameFragment(MemoryBlockUtil.java:613)
	at ghidra.app.util.MemoryBlockUtil.createUninitializedBlock(MemoryBlockUtil.java:149)
	at fi.gekkio.ghidraboy.Ghidra90Compat.createUninitializedBlock(Ghidra90Compat.java:33)
	at fi.gekkio.ghidraboy.GameBoyUtils.addHardwareBlocks(GameBoyUtils.java:38)
	at fi.gekkio.ghidraboy.GameBoyLoader.loadProgram(GameBoyLoader.java:133)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:114)
	at ghidra.plugin.importer.ImporterUtilities.doSingleImport(ImporterUtilities.java:360)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$6(ImporterDialog.java:363)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:93)
	at ghidra.util.task.Task.monitoredRun(Task.java:128)
	at ghidra.util.task.TaskLauncher.lambda$startBackgroundThread$2(TaskLauncher.java:315)
	at java.base/java.lang.Thread.run(Thread.java:835)

---------------------------------------------------
Build Date: 2019-May-16 1545 EDT
Ghidra Version: 9.0.4
Java Home: C:\Program Files\Java\jdk-12.0.1
JVM Version: Oracle Corporation 12.0.1
OS: Windows 10 10.0 amd64
Workstation: [omitted]
```

**Comment by Gekkio** [comment]
Unfortunately I couldn't replicate this issue, so it might be an OS / environment -specific problem or possibly a Ghidra bug.

Now that Ghidra 9.1 has finally been released, I've decided to drop support for 9.0.x. Please reopen this issue or open a new issue if you have any problems with Ghidra 9.1 + latest GhidraBoy :sweat_smile:
